import { z } from "zod";
import {
    nameSchema,
    emailLowercaseSchema,
    optionalPhoneSchema,
    estadoUsuarioSchema,
    tipoDocumentoSchema,
    documentSchema,
    optionalDateSchema,
    generoSchema,
    optionalLongText,
    nonNegativeIntSchema,
    requiredBigIntSchema,
    nivelIdiomaSchema,
    optionalSelect,
} from "@/shared/validations/sharedSchemas";

export const guideSchema = z.object({
    firstName: nameSchema("Nombre es obligatorio."),
    lastName: nameSchema("Apellido es obligatorio."),
    correo: emailLowercaseSchema,
    telefono: optionalPhoneSchema,
    estado: estadoUsuarioSchema,
    tipo_documento: tipoDocumentoSchema,
    numero_documento: documentSchema,
    fecha_nacimiento: optionalDateSchema(),
    genero: generoSchema,
    nacionalidad: optionalLongText(100),
    pais_residencia: optionalLongText(100),
    ciudad_residencia: optionalLongText(100),
    direccion: optionalLongText(255),
    especialidad: optionalLongText(150),
    experiencia_anios: nonNegativeIntSchema("Años experiencia").optional().or(z.literal("")).transform(v => v === "" ? null : Number(v)),
    certificaciones: optionalLongText(),
    foto_url: optionalLongText(500),
    disponibilidad: z.boolean().default(true),
    activo: z.boolean().default(true),
    biografia: optionalLongText(),
    idiomas: z.array(z.object({
        id_idioma: requiredBigIntSchema("Seleccione idioma."),
        nivel: nivelIdiomaSchema,
    })).default([]),
    certificaciones_puente: z.array(z.object({
        id_certificacion: requiredBigIntSchema(),
        fecha_obtencion: optionalDateSchema(),
        fecha_vencimiento: optionalDateSchema(),
        numero_certificado: optionalLongText(50),
    })).default([]),
});
